"""Supplementary data workbook (paper/build/SI_data_v2.xlsx), built from run artifacts only.

Sheets: About | Assumptions (every TEA parameter with kind/source) | Numbers (every number in the manuscript with
its artifact path) | ESI_numbers (every number in the ESI prose) | Fig1_funnel | Fig2_ml | Fig3a_reliability |
Fig3b_umlip | Fig4a_sweep | Fig4b_breakeven | Fig5_candidates | Pareto | Candidates_all (1,256 rows) |
FigS1..FigS8 (data behind the ESI figures, from figures/si_data/) | References
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
R = ROOT / "runs"
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(HERE))
from paper_numbers import fmt  # noqa: E402
from pipeline.tea_params import ELEMENT_PRICE, LEGACY_UNSOURCED, P  # noqa: E402


def j(rel):
    return json.loads((R / rel).read_text(encoding="utf-8"))


# Used only where the manuscript sources are absent (the public repository ships code and data, not the
# manuscript text). In the authoring repo the title and author block are read from the manuscript front matter,
# and the build refuses to run if this copy of the title has drifted from it.
PUBLIC_TITLE = ("An end-to-end audit of machine-learning techno-economic screening for lead-free double "
                "perovskite photovoltaics")
PUBLIC_AUTHOR = {"author": "Havid Aqoma", "orcid": "0000-0003-1264-1916", "email": "",
                 "affiliations": ["Xiamen University Malaysia"]}


def front_matter() -> tuple[str, dict]:
    ms = HERE / "manuscript_part1.md"
    if not ms.exists():
        return PUBLIC_TITLE, PUBLIC_AUTHOR
    from build_paper import author_meta          # author block has one source: the manuscript front matter
    front = ms.read_text(encoding="utf-8")
    title = re.search(r'^title:\s*"(.*)"', front, re.M).group(1)    # title has one source as well
    if title != PUBLIC_TITLE:
        raise SystemExit(f"make_si_excel.PUBLIC_TITLE is stale; set it to the manuscript title:\n{title}")
    return title, author_meta(front)


def main() -> Path:
    out = HERE / "build" / "SI_data_v2.xlsx"
    out.parent.mkdir(parents=True, exist_ok=True)
    N = json.loads((HERE / "numbers.json").read_text(encoding="utf-8"))
    title, a = front_matter()
    about = pd.DataFrame({"field": ["Title", "Author", "ORCID", "E-mail"]
                          + [f"Affiliation {i + 1}" for i in range(len(a["affiliations"]))] + ["Contents", "Provenance"],
                          "value": [title, a["author"], a["orcid"], a["email"],
                                    *a["affiliations"], "Raw data behind every figure and every number in the "
                                    "manuscript and the ESI (sheets FigS1 to FigS8 hold the ESI figure data)", "Generated by paper/make_si_excel.py from runs/ artifacts; see Numbers "
                                    "sheet for the artifact path of each value. Code and data: "
                                    "https://github.com/havidaqoma/perovskite-screening-ml-tea"]})
    rows = []
    for k, v in P.items():
        val = v.get("value", {kk: v[kk] for kk in ("msp", "mmp", "low", "med", "high", "grid", "alt") if kk in v})
        rows.append({"parameter": k, "value": json.dumps(val, default=float), "unit": v.get("unit", ""),
                     "kind": v["kind"], "source": v.get("src", ""), "quote_or_formula": v.get("quote") or v.get("formula") or v.get("note", "")})
    for el, (pr, note) in ELEMENT_PRICE.items():
        rows.append({"parameter": f"price_{el}", "value": round(pr, 2), "unit": "$/kg", "kind": "direct/derived",
                     "source": "USGS24", "quote_or_formula": note})
    for el, pr in LEGACY_UNSOURCED.items():
        rows.append({"parameter": f"price_{el}", "value": pr, "unit": "$/kg", "kind": "unsourced (legacy)",
                     "source": "-", "quote_or_formula": "immaterial: absorber cost changes LCOE by < 5%"})
    assumptions = pd.DataFrame(rows)
    numbers = pd.DataFrame([{"token": k, "printed": fmt(v), "value": v["value"], "artifact": v["src"]} for k, v in N.items()])

    fg, fs = j("legacy_april/metrics/funnel_generate.json"), j("legacy_april/metrics/funnel_screen.json")
    sc, stb, pa = j("v2/metrics/screen_v2.json"), j("v2/metrics/stability_v2.json"), j("v2/metrics/pareto.json")
    ff = sc["funnel_fail_counts"]
    fig1 = pd.DataFrame([
        ("legacy", "generated", fg["n_generated"]), ("legacy", "charge balanced", fg["n_charge_balanced"]),
        ("legacy", "legacy steric", fg["n_steric"]), ("legacy", "legacy ML window", fs["n_candidates"]),
        ("v2", "generated", fg["n_generated"]), ("v2", "charge balanced", fg["n_charge_balanced"]),
        ("v2", "oxidation-state radii + tau", fg["n_charge_balanced"] - ff["tau_not_perovskite"] - ff["no_oxidation_state_assignment"]),
        ("v2", "gatekeeper", sc["n_v2_candidates"]),
        ("v2", "likely stable or known", stb["status_counts"]["stable_likely"] + stb["status_counts"]["known_mp"]),
        ("v2", "pareto front", pa["n_front1"])], columns=["pipeline", "stage", "n"])
    ev = j("v2/metrics/ml_eval_v2.json")
    fig2 = pd.DataFrame([{"split": r["split"], "task": r["task"], "model": r["model"],
                          "mae_pooled": r.get("mae_pooled"), "roc_auc": r.get("roc_auc")} for r in ev["results"]])
    ro = j("v2/metrics/roost_chemsys_gap_semi.json")
    fig2 = pd.concat([fig2, pd.DataFrame([{"split": "chemsys", "task": "gap_semi", "model": "roost", "mae_pooled": ro["mae_pooled"]}])])
    la = j("v2/metrics/leakage_audit.json")
    fig2 = pd.concat([fig2, pd.DataFrame([{"split": f"april_{k}", "task": "gap", "model": "xgb_legacy",
                                           "mae_pooled": v["bg_mae_eV"]} for k, v in la.items()])])
    conf = pd.DataFrame([{"split": s, "fold": i, "coverage": c} for s in ("random", "chemsys")
                         for i, c in enumerate(ev["conformal"][s]["coverage_folds"])])
    rel = pd.DataFrame([{"bin": k, **v} for k, v in stb["control"]["reliability"].items()])
    um = pd.read_csv(R / "v2/stability/umlip.csv")
    sweep = pd.read_csv(R / "v2/tea_v2/efficiency_sweep.csv")
    be = pd.read_csv(R / "v2/tea_v2/breakeven_efficiency.csv")
    t = j("v2/metrics/tea_v2.json")["e5_candidates"]
    fig5 = pd.DataFrame([{"scenario": k, "definition": t["scenario_definitions"][k],
                          "expected_competitive_and_stable": t["expected_n_competitive_and_stable"][k],
                          "with_mace_veto": t["expected_n_competitive_and_stable_umlip"][k],
                          "max_p": t["max_p_competitive"][k]} for k in ("demonstrated", "realistic", "optimistic", "ceiling")])
    pareto = pd.read_csv(R / "v2/pareto/pareto.csv")
    cands = pd.read_csv(R / "v2/tea_v2/candidate_lcoe.csv")
    refs = pd.DataFrame(json.loads((HERE / "refs_verified.json").read_text()))[["key", "doi", "title", "year", "venue", "claim"]]
    si_refs = HERE / "si_refs_verified.json"
    if si_refs.exists():
        refs = pd.concat([refs, pd.DataFrame(json.loads(si_refs.read_text()))[["key", "doi", "title", "year", "venue",
                                                                                 "claim"]]])
    SN = json.loads((HERE / "si_numbers.json").read_text(encoding="utf-8"))
    si_numbers = pd.DataFrame([{"token": k, "printed": fmt(v), "value": v["value"], "source": v["src"]}
                               for k, v in SN.items()])
    si_figs = sorted((HERE / "figures" / "si_data").glob("figS*.csv"))   # written by make_si_figures.py
    if len(si_figs) != 8:
        raise SystemExit(f"expected 8 ESI figure-data files, found {[p.name for p in si_figs]}: run make_si_figures.py")

    with pd.ExcelWriter(out, engine="openpyxl") as xw:
        for name, df in (("About", about), ("Assumptions", assumptions), ("Numbers", numbers),
                         ("ESI_numbers", si_numbers), ("Fig1_funnel", fig1),
                         ("Fig2_ml", fig2), ("Fig2c_conformal", conf), ("Fig3a_reliability", rel), ("Fig3b_umlip", um),
                         ("Fig4a_sweep", sweep), ("Fig4b_breakeven", be), ("Fig5_candidates", fig5), ("Pareto", pareto),
                         ("Candidates_all", cands),
                         *((p.stem.split("_")[0].replace("figS", "FigS") + "_" + p.stem.split("_", 1)[1][:20],
                            pd.read_csv(p)) for p in si_figs),
                         ("References", refs)):
            df.to_excel(xw, sheet_name=name, index=False)
    return out


if __name__ == "__main__":
    p = main()
    import openpyxl
    wb = openpyxl.load_workbook(p, read_only=True)
    print(p, {ws.title: ws.max_row for ws in wb.worksheets})
